server:
  port: 8082

spring:
  application:
    name: kyc-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        # comment
        include: '*'
  #        include: health, info, metrics, env, beans
  endpoint:
    health:
      show-details: always